
package net.mehdi.activemqjms.wsdlReq;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "SOnePersistRequest", targetNamespace = "http://sonePersistRequest.ws.sofac.ma")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SOnePersistRequest {


    /**
     * 
     * @param request
     * @return
     *     returns net.mehdi.activemqjms.wsdlReq.PersistResponse.OutputData
     */
    @WebMethod
    @WebResult(name = "OutputData", targetNamespace = "")
    @RequestWrapper(localName = "persist", targetNamespace = "http://sonePersistRequest.ws.sofac.ma", className = "net.mehdi.activemqjms.wsdlReq.Persist")
    @ResponseWrapper(localName = "persistResponse", targetNamespace = "http://sonePersistRequest.ws.sofac.ma", className = "net.mehdi.activemqjms.wsdlReq.PersistResponse")
    public PersistResponse.OutputData persist(
        @WebParam(name = "Request", targetNamespace = "")
        Persist.Request request);

}
