package net.mehdi.activemqjms.mappers.res_mappers;

import net.mehdi.activemqjms.dtos.res_dtos.RecordRespDTO;
import net.mehdi.activemqjms.entities.res_entities.RecordRRRes;
import net.mehdi.activemqjms.utils.DoubleUtils;
import net.mehdi.activemqjms.utils.IntegerUtils;

public class RecordRRRespMapper {
    public static RecordRRRes toEntity(RecordRespDTO dto) {
        if (dto == null) {
            return null;
        }

        RecordRRRes entity = new RecordRRRes();
        entity.setRcmo010(dto.getRCMO010().getV());
        entity.setRcmo011(dto.getRCMO011().getV());
        entity.setRcmo012(dto.getRCMO012().getV());
        entity.setRcmo013(dto.getRCMO013().getV());
        entity.setRcmo014(dto.getRCMO014().getV());
        entity.setRcmo015(dto.getRCMO015().getV());
        entity.setRcmo016(dto.getRCMO016().getV());
        entity.setRcmo017(dto.getRCMO017().getV());
        entity.setRcmo018(dto.getRCMO018().getV());
        entity.setRcmo019(dto.getRCMO019().getV());
        entity.setRcmo020(dto.getRCMO020().getV());
        entity.setRcmo021(dto.getRCMO021().getV());
        entity.setRcmo021ForcageAbb(dto.getRCMO021ForcageABB().getV());
        entity.setRcmo022(dto.getRCMO022().getV());
        entity.setRcmo023(dto.getRCMO023().getV());
        entity.setRcmo024(dto.getRCMO024().getV());
        entity.setRcmo025(dto.getRCMO025().getV());
        entity.setRcmo026(dto.getRCMO026().getV());
        entity.setRcmo027(dto.getRCMO027().getV());
        entity.setRcmo028(dto.getRCMO028().getV());
        entity.setRcmo029(dto.getRCMO029().getV());
        entity.setRcmo030(dto.getRCMO030().getV());
        entity.setRcmo031(dto.getRCMO031().getV());
        entity.setRcmo032(dto.getRCMO032().getV());
        entity.setRcmo033(dto.getRCMO033().getV());
        entity.setRcmo034(dto.getRCMO034().getV());
        entity.setRcmo035(dto.getRCMO035().getV());
        entity.setRcmo036(dto.getRCMO036().getV());
        entity.setRcmo037(dto.getRCMO037().getV());
        entity.setRcmo038(dto.getRCMO038().getV());
        entity.setRcmo039(dto.getRCMO039().getV());
        entity.setRcmo040(dto.getRCMO040().getV());
        entity.setRcmo041(dto.getRCMO041().getV());
        entity.setRcmo042(dto.getRCMO042().getV());
        entity.setRcmo043(dto.getRCMO043().getV());
        entity.setRcmo044(dto.getRCMO044().getV());
        entity.setRcmo045(dto.getRCMO045().getV());
        entity.setRcmo046(dto.getRCMO046().getV());
        entity.setRcmo047(dto.getRCMO047().getV());
        entity.setRcmo048(dto.getRCMO048().getV());
        entity.setRcmo049(dto.getRCMO049().getV());
        entity.setRcmo050(dto.getRCMO050().getV());
        entity.setRmmo010(dto.getRMMO010().getV());
        entity.setRmmo011(dto.getRMMO011().getV());
        entity.setRmmo012(dto.getRMMO012().getV());
        entity.setRmmo013(dto.getRMMO013().getV());
        entity.setRmmo014(dto.getRMMO014().getV());
        entity.setRmmo015(dto.getRMMO015().getV());
        entity.setRmmo016(dto.getRMMO016().getV());
        entity.setRmmo017(dto.getRMMO017().getV());
        entity.setRmmo018(dto.getRMMO018().getV());
        entity.setRmmo019(dto.getRMMO019().getV());
        entity.setRmmo020(dto.getRMMO020().getV());
        entity.setRmmo021(dto.getRMMO021().getV());
        entity.setRmmo021(dto.getRMMO021().getV());
        entity.setRmmo021ForcageAbb(dto.getRMMO021ForcageABB().getV());
        entity.setRmmo022(dto.getRMMO022().getV());
        entity.setRmmo023(dto.getRMMO023().getV());
        entity.setRmmo024(dto.getRMMO024().getV());
        entity.setRmmo025(dto.getRMMO025().getV());
        entity.setRmmo026(dto.getRMMO026().getV());
        entity.setRmmo027(dto.getRMMO027().getV());
        entity.setRmmo028(dto.getRMMO028().getV());
        entity.setRmmo029(dto.getRMMO029().getV());
        entity.setRmmo030(dto.getRMMO030().getV());
        entity.setRmmo031(dto.getRMMO031().getV());
        entity.setRmmo032(dto.getRMMO032().getV());
        entity.setRmmo033(dto.getRMMO033().getV());
        entity.setRmmo034(dto.getRMMO034().getV());
        entity.setRmmo035(dto.getRMMO035().getV());
        entity.setRmmo036(dto.getRMMO036().getV());
        entity.setRmmo037(dto.getRMMO037().getV());
        entity.setRmmo038(dto.getRMMO038().getV());
        entity.setRmmo039(dto.getRMMO039().getV());
        entity.setRmmo040(dto.getRMMO040().getV());
        entity.setRmmo041(dto.getRMMO041().getV());
        entity.setRmmo042(dto.getRMMO042().getV());
        entity.setRmmo043(dto.getRMMO043().getV());
        entity.setRmmo044(dto.getRMMO044().getV());
        entity.setRmmo045(dto.getRMMO045().getV());
        entity.setRmmo046(dto.getRMMO046().getV());
        entity.setRmmo047(dto.getRMMO047().getV());
        entity.setRmmo048(dto.getRMMO048().getV());
        entity.setRmmo049(dto.getRMMO049().getV());
        entity.setRmmo050(dto.getRMMO050().getV());
        entity.setVoutAge(DoubleUtils.parseDouble(dto.getVOUTAge().getV()));
        entity.setVoutAgeDureePret(DoubleUtils.parseDouble(dto.getVOUTAgeDureePret().getV()));
        entity.setVoutAncienneteActPart(DoubleUtils.parseDouble(dto.getVOUTAncienneteActivitePart().getV()));
        entity.setVoutAncienneteBancaire(DoubleUtils.parseDouble(dto.getVOUTAncienneteBancaire().getV()));
        entity.setVoutAncienneteTeteSoci(DoubleUtils.parseDouble(dto.getVOUTAncienneteTeteSociete().getV()));
        entity.setVoutCodeBanque(dto.getVOUTCodeBanque().getV());
        entity.setVoutEmployeur(dto.getVOUTEmployeur().getV());
        entity.setVoutEncoursAncienneAff(DoubleUtils.parseDouble(dto.getVOUTEncoursAncienneAffaire().getV()));
        entity.setVoutEncoursClientHisto(DoubleUtils.parseDouble(dto.getVOUTEncoursClientHISTO().getV()));
        entity.setVoutEncoursCompensees(DoubleUtils.parseDouble(dto.getVOUTEncoursCompensees().getV()));
        entity.setVoutEncoursProduitAssu(DoubleUtils.parseDouble(dto.getVOUTEncoursProduitASSU().getV()));
        entity.setVoutEncoursProduitAuto(DoubleUtils.parseDouble(dto.getVOUTEncoursProduitAUTO().getV()));
        entity.setVoutEncoursProduitEdm(DoubleUtils.parseDouble(dto.getVOUTEncoursProduitEDM().getV()));
        entity.setVoutEncoursProduitMou(DoubleUtils.parseDouble(dto.getVOUTEncoursProduitMOU().getV()));
        entity.setVoutEncoursProduitPp(DoubleUtils.parseDouble(dto.getVOUTEncoursProduitPP().getV()));
        entity.setVoutFichageChequiersAnn(DoubleUtils.parseDouble(dto.getVOUTFichageChequiersAnnule().getV()));
        entity.setVoutFichageChequiersEchu(DoubleUtils.parseDouble(dto.getVOUTFichageChequiersEchu().getV()));
        entity.setVoutFichageChequEnCours(DoubleUtils.parseDouble(dto.getVOUTFichageChequiersEncours().getV()));
        entity.setVoutFichageChequiersRegu(DoubleUtils.parseDouble(dto.getVOUTFichageChequiersRegularise().getV()));
        entity.setVoutIdentifiantClient(dto.getVOUTIdentifiantClient().getV());
        entity.setVoutImpayeFlag(dto.getVOUTImpayeFlag().getV());
        entity.setVoutMarche(dto.getVOUTMarche().getV());
        entity.setVoutMinimumVital(DoubleUtils.parseDouble(dto.getVOUTMinimumVital().getV()));
        entity.setVoutMontantRevenu(DoubleUtils.parseDouble(dto.getVOUTMontantRevenu().getV()));
        entity.setVoutMouvementsCredit(DoubleUtils.parseDouble(dto.getVOUTMouvementsCrediteurs().getV()));
        entity.setVoutNbrImpayes(IntegerUtils.parseInteger(dto.getVOUTNbrImpayes().getV()));
        entity.setVoutNbrImpayes12(IntegerUtils.parseInteger(dto.getVOUTNbrImpayes12().getV()));
        entity.setVoutNbrIncidents(IntegerUtils.parseInteger(dto.getVOUTNbrIncidents().getV()));
        entity.setVoutNouveauClienton(dto.getVOUTNouveauClientON().getV());
        entity.setVoutProfession(dto.getVOUTProfession().getV());
        entity.setVoutRevenuTotal(DoubleUtils.parseDouble(dto.getVOUTRevenuTotal().getV()));
        entity.setVoutRole(dto.getVOUTRole().getV());
        entity.setVoutSegment(dto.getVOUTSegment().getV());
        entity.setVoutSexe(dto.getVOUTSexe().getV());
        entity.setVoutSituationLogement(dto.getVOUTSituationLogement().getV());
        entity.setVoutSoldeImpayes(DoubleUtils.parseDouble(dto.getVOUTSoldeImpayes().getV()));
        entity.setVoutSoldeMoyen3mois(DoubleUtils.parseDouble(dto.getVOUTSoldeMoyen3Mois().getV()));
        entity.setVoutTauxEndettement(DoubleUtils.parseDouble(dto.getVOUTTauxEndettement().getV()));
        entity.setVoutTemporisation(DoubleUtils.parseDouble(dto.getVOUTTemporisation().getV()));
        entity.setVoutTypeClient(dto.getVOUTTypeClient().getV());
        entity.setVoutCsp(dto.getVOUTCSP().getV());
        entity.setVoutCspCode(dto.getVOUTCSPCode().getV());
//128
        return entity;
    }
}
