package net.mehdi.activemqjms.mappers.res_mappers;

import net.mehdi.activemqjms.dtos.res_dtos.RecordNRRespDTO;
import net.mehdi.activemqjms.entities.res_entities.RecordNRRes;
import net.mehdi.activemqjms.utils.DateUtils;
import net.mehdi.activemqjms.utils.DoubleUtils;
import net.mehdi.activemqjms.utils.IntegerUtils;

public class RecordNRRespMapper {

    public static RecordNRRes toEntity(RecordNRRespDTO dto) {
        if (dto == null) {
            return null;
        }
        RecordNRRes entity = new RecordNRRes();

        entity.setGrilleClasseAffectVar0(dto.getGRILLEClasseAffecteeVar0().getV());
        entity.setGrilleClasseAffectVar1(dto.getGRILLEClasseAffecteeVar1().getV());
        entity.setGrilleClasseAffectVar10(dto.getGRILLEClasseAffecteeVar10().getV());
        entity.setGrilleClasseAffectVar11(dto.getGRILLEClasseAffecteeVar11().getV());
        entity.setGrilleClasseAffectVar12(dto.getGRILLEClasseAffecteeVar12().getV());
        entity.setGrilleClasseAffectVar13(dto.getGRILLEClasseAffecteeVar13().getV());
        entity.setGrilleClasseAffectVar14(dto.getGRILLEClasseAffecteeVar14().getV());
        entity.setGrilleClasseAffectVar15(dto.getGRILLEClasseAffecteeVar15().getV());
        entity.setGrilleClasseAffectVar16(dto.getGRILLEClasseAffecteeVar16().getV());
        entity.setGrilleClasseAffectVar17(dto.getGRILLEClasseAffecteeVar17().getV());
        entity.setGrilleClasseAffectVar18(dto.getGRILLEClasseAffecteeVar18().getV());
        entity.setGrilleClasseAffectVar19(dto.getGRILLEClasseAffecteeVar19().getV());
        entity.setGrilleClasseAffectVar2(dto.getGRILLEClasseAffecteeVar2().getV());
        entity.setGrilleClasseAffectVar20(dto.getGRILLEClasseAffecteeVar20().getV());
        entity.setGrilleClasseAffectVar3(dto.getGRILLEClasseAffecteeVar3().getV());
        entity.setGrilleClasseAffectVar4(dto.getGRILLEClasseAffecteeVar4().getV());
        entity.setGrilleClasseAffectVar5(dto.getGRILLEClasseAffecteeVar5().getV());
        entity.setGrilleClasseAffectVar6(dto.getGRILLEClasseAffecteeVar6().getV());
        entity.setGrilleClasseAffectVar7(dto.getGRILLEClasseAffecteeVar7().getV());
        entity.setGrilleClasseAffectVar8(dto.getGRILLEClasseAffecteeVar8().getV());
        entity.setGrilleClasseAffectVar9(dto.getGRILLEClasseAffecteeVar9().getV());

        entity.setGrilleNoteVar0(IntegerUtils.parseInteger(dto.getGRILLENoteVar0().getV()));
        entity.setGrilleNoteVar1(IntegerUtils.parseInteger(dto.getGRILLENoteVar1().getV()));
        entity.setGrilleNoteVar10(IntegerUtils.parseInteger(dto.getGRILLENoteVar10().getV()));
        entity.setGrilleNoteVar11(IntegerUtils.parseInteger(dto.getGRILLENoteVar11().getV()));
        entity.setGrilleNoteVar12(IntegerUtils.parseInteger(dto.getGRILLENoteVar12().getV()));
        entity.setGrilleNoteVar13(IntegerUtils.parseInteger(dto.getGRILLENoteVar13().getV()));
        entity.setGrilleNoteVar14(IntegerUtils.parseInteger(dto.getGRILLENoteVar14().getV()));
        entity.setGrilleNoteVar15(IntegerUtils.parseInteger(dto.getGRILLENoteVar15().getV()));
        entity.setGrilleNoteVar16(IntegerUtils.parseInteger(dto.getGRILLENoteVar16().getV()));
        entity.setGrilleNoteVar17(IntegerUtils.parseInteger(dto.getGRILLENoteVar17().getV()));
        entity.setGrilleNoteVar18(IntegerUtils.parseInteger(dto.getGRILLENoteVar18().getV()));
        entity.setGrilleNoteVar19(IntegerUtils.parseInteger(dto.getGRILLENoteVar19().getV()));
        entity.setGrilleNoteVar2(IntegerUtils.parseInteger(dto.getGRILLENoteVar2().getV()));
        entity.setGrilleNoteVar20(IntegerUtils.parseInteger(dto.getGRILLENoteVar20().getV()));
        entity.setGrilleNoteVar3(IntegerUtils.parseInteger(dto.getGRILLENoteVar3().getV()));
        entity.setGrilleNoteVar4(IntegerUtils.parseInteger(dto.getGRILLENoteVar4().getV()));
        entity.setGrilleNoteVar5(IntegerUtils.parseInteger(dto.getGRILLENoteVar5().getV()));
        entity.setGrilleNoteVar6(IntegerUtils.parseInteger(dto.getGRILLENoteVar6().getV()));
        entity.setGrilleNoteVar7(IntegerUtils.parseInteger(dto.getGRILLENoteVar7().getV()));
        entity.setGrilleNoteVar8(IntegerUtils.parseInteger(dto.getGRILLENoteVar8().getV()));
        entity.setGrilleNoteVar9(IntegerUtils.parseInteger(dto.getGRILLENoteVar9().getV()));


        entity.setGrilleVariable0(dto.getGRILLEVariable0().getV());
        entity.setGrilleVariable1(dto.getGRILLEVariable1().getV());
        entity.setGrilleVariable10(dto.getGRILLEVariable10().getV());
        entity.setGrilleVariable11(dto.getGRILLEVariable11().getV());
        entity.setGrilleVariable12(dto.getGRILLEVariable12().getV());
        entity.setGrilleVariable13(dto.getGRILLEVariable13().getV());
        entity.setGrilleVariable14(dto.getGRILLEVariable14().getV());
        entity.setGrilleVariable15(dto.getGRILLEVariable15().getV());
        entity.setGrilleVariable16(dto.getGRILLEVariable16().getV());
        entity.setGrilleVariable17(dto.getGRILLEVariable17().getV());
        entity.setGrilleVariable18(dto.getGRILLEVariable18().getV());
        entity.setGrilleVariable19(dto.getGRILLEVariable19().getV());
        entity.setGrilleVariable2(dto.getGRILLEVariable2().getV());
        entity.setGrilleVariable20(dto.getGRILLEVariable20().getV());
        entity.setGrilleVariable3(dto.getGRILLEVariable3().getV());
        entity.setGrilleVariable4(dto.getGRILLEVariable4().getV());
        entity.setGrilleVariable5(dto.getGRILLEVariable5().getV());
        entity.setGrilleVariable6(dto.getGRILLEVariable6().getV());
        entity.setGrilleVariable7(dto.getGRILLEVariable7().getV());
        entity.setGrilleVariable8(dto.getGRILLEVariable8().getV());
        entity.setGrilleVariable9(dto.getGRILLEVariable9().getV());

        entity.setGrilleAligned(IntegerUtils.parseInteger(dto.getGRILLEALIGNED().getV()));
        entity.setGrilleObjCode(dto.getGRILLEOBJCODE().getV());
        entity.setGrilleRaw(IntegerUtils.parseInteger(dto.getGRILLERAW().getV()));
        entity.setNotationFin(DoubleUtils.parseDouble(dto.getNOTATIONFIN().getV()));
        entity.setNotationFin0100(DoubleUtils.parseDouble(dto.getNOTATIONFIN0100().getV()));
        entity.setNotationHom(DoubleUtils.parseDouble(dto.getNOTATIONHOM().getV()));
        entity.setNotationHom0100(DoubleUtils.parseDouble(dto.getNOTATIONHOM0100().getV()));
        entity.setNoteScoreOppm(DoubleUtils.parseDouble(dto.getNoteScoreOPPM().getV()));
        entity.setRcso001(dto.getRCSO001().getV());
        entity.setRcso002(dto.getRCSO002().getV());
        entity.setRcso003(dto.getRCSO003().getV());
        entity.setRcso003ForcageAbb(dto.getRCSO003ForcageABB().getV());
        entity.setRcso004(dto.getRCSO004().getV());
        entity.setRcso004ForcageAbb(dto.getRCSO004ForcageABB().getV());
        entity.setRcso005(dto.getRCSO005().getV());
        entity.setRcso006(dto.getRCSO006().getV());
        entity.setRcso007(dto.getRCSO007().getV());
        entity.setRcso008(dto.getRCSO008().getV());
        entity.setRcso009(dto.getRCSO009().getV());
        entity.setRcso051(dto.getRCSO051().getV());
        entity.setRcso052(dto.getRCSO052().getV());
        entity.setRcso053(dto.getRCSO053().getV());
        entity.setRcso054(dto.getRCSO054().getV());
        entity.setRcso055(dto.getRCSO055().getV());
        entity.setRcso056(dto.getRCSO056().getV());
        entity.setRcso057(dto.getRCSO057().getV());
        entity.setRcso058(dto.getRCSO058().getV());
        entity.setRcso059(dto.getRCSO059().getV());
        entity.setRcso060(dto.getRCSO060().getV());
        entity.setRmso001(dto.getRMSO001().getV());
        entity.setRmso002(dto.getRMSO002().getV());
        entity.setRmso003(dto.getRMSO003().getV());
        entity.setRmso003ForcageAbb(dto.getRMSO003ForcageABB().getV());
        entity.setRmso004(dto.getRMSO004().getV());
        entity.setRmso004ForcageAbb(dto.getRMSO004ForcageABB().getV());
        entity.setRmso005(dto.getRMSO005().getV());
        entity.setRmso006(dto.getRMSO006().getV());
        entity.setRmso007(dto.getRMSO007().getV());
        entity.setRmso008(dto.getRMSO008().getV());
        entity.setRmso009(dto.getRMSO009().getV());
        entity.setRmso051(dto.getRMSO051().getV());
        entity.setRmso052(dto.getRMSO052().getV());
        entity.setRmso053(dto.getRMSO053().getV());
        entity.setRmso054(dto.getRMSO054().getV());
        entity.setRmso055(dto.getRMSO055().getV());
        entity.setRmso056(dto.getRMSO056().getV());
        entity.setRmso057(dto.getRMSO057().getV());
        entity.setRmso058(dto.getRMSO058().getV());
        entity.setRmso059(dto.getRMSO059().getV());
        entity.setRmso060(dto.getRMSO060().getV());

        entity.setScOrating(DoubleUtils.parseDouble(dto.getScorating().getV()));
        entity.setScoreOp(DoubleUtils.parseDouble(dto.getScoreOP().getV()));
        entity.setScoreRat(DoubleUtils.parseDouble(dto.getScoreRAT().getV()));
        entity.setVoutAgeVehicule(DoubleUtils.parseDouble(dto.getVOUTAgeVehicule().getV()));
        entity.setVoutAgeVehiculeDuree(DoubleUtils.parseDouble(dto.getVOUTAgeVehiculeDuree().getV()));
        entity.setVoutAnciActiviteEntr(DoubleUtils.parseDouble(dto.getVOUTAncienneteActiviteEntr().getS()));
        entity.setVoutCategorieAffaire(dto.getVOUTCategorieAffaire().getV());
        entity.setVoutCodeAgence(dto.getVOUTCodeAgence().getV());
        entity.setVoutCodeNiveauPouvoir(dto.getVOUTCodeNiveauPouvoir().getV());
        entity.setVoutCoherence(dto.getVOUTCoherence().getV());
        entity.setVoutDateDemande(DateUtils.toDate(dto.getVOUTDateDemande().getV()) );
        entity.setVoutDecisionFinale(dto.getVOUTDecisionFinale().getV());
        entity.setVoutDecFinForcageAbb(dto.getVOUTDecisionFinaleForcageABB().getS());
        entity.setVoutDecProposAjuste(dto.getVOUTDecisionPropositionAjuste().getV());
        entity.setVoutDureeAjuste(DoubleUtils.parseDouble(dto.getVOUTDureeAjuste().getV()));
        entity.setVoutDureeDemande(IntegerUtils.parseInteger(dto.getVOUTDureeDemande().getV()));
        entity.setVoutEncoursClientFutur(DoubleUtils.parseDouble(dto.getVOUTEncoursClientFUTUR().getV()));
        entity.setVoutFlagGarantie(dto.getVOUTFlagGarantie().getV());
        entity.setVoutMensualiteAjuste(DoubleUtils.parseDouble(dto.getVOUTMensualiteAjuste().getV()));
        entity.setVoutMensualiteDemande(DoubleUtils.parseDouble(dto.getVOUTMensualiteDemande().getV()));
        entity.setVoutMontantAjuste(DoubleUtils.parseDouble(dto.getVOUTMontantAjuste().getV()));
        entity.setVoutMontantDemande(DoubleUtils.parseDouble(dto.getVOUTMontantDemande().getV()));
        entity.setVoutNiveauPouvoir(dto.getVOUTNiveauPouvoir().getV());
        entity.setVoutOutputRegles(dto.getVOUTOutputRegles().getV());
        entity.setVoutOutReglForcageAbb(dto.getVOUTOutputReglesForcageABB().getS());
        entity.setVoutRandomNumber(dto.getVOUTRandomNumber().getV());
        entity.setVoutScore(dto.getVOUTScore().getV());
        entity.setVoutSocieteGestion(dto.getVOUTSocieteGestion().getV());
        entity.setVoutTauxApport(DoubleUtils.parseDouble(dto.getVOUTTauxApport().getS()));
        entity.setVoutNumDemande(dto.getVOUTNumeroDemande().getV());
        entity.setVoutNumLancement(IntegerUtils.parseInteger(dto.getVOUTNUMLANCEMENT().getV()));
        return entity;
    }
}
